version: "2"
services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    links:
      - app
    ports:
      - "3002:80"

  postgres:
    extends:
      file: base.yml
      service: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data/

  redis:
    extends:
      file: base.yml
      service: redis

  app:
    restart: always
    extends:
      file: base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres
    env_file: .env

  worker:
    extends:
      file: base.yml
      service: worker
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres

  beat:
    extends:
      file: base.yml
      service: beat
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - redis
      - postgres
  
  websockets_worker:
    extends:
      file: base.yml
      service: websockets_worker
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - app
      - redis
      
  daphne:
    extends:
      file: base.yml
      service: daphne
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - app
      - redis



  